name: flutter_reportx
description: TalentPulse - AI Performance Intelligence Dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  fl_chart: ^0.69.2
  uuid: ^4.0.0
  flutter_animate: ^4.2.0
  intl: ^0.19.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
